// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzoyahdxekublnqcozlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6b3lhaGR4ZWt1YmxucWNvemxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODgxNjQsImV4cCI6MjA3MDM2NDE2NH0.wwY6nEUtHNnDjQrk7EicDWLkbh_1tQb7uI0Kcr8K4XQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});