// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use Vite env vars (exposed to client must be prefixed with VITE_)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://wzoyahdxekublnqcozlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6b3lhaGR4ZWt1YmxucWNvemxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODgxNjQsImV4cCI6MjA3MDM2NDE2NH0.wwY6nEUtHNnDjQrk7EicDWLkbh_1tQb7uI0Kcr8K4XQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use a loose generic for now to avoid TypeScript errors until types.ts is regenerated
export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
